### ISSUE TITLE
Who does the performance measurement and scoring?

### ISSUE THREAD

**Issue by dwagelaar** [FTSRG/trainbenchmark-ttc#9]
Who does the performance measurement and scoring of which tool, and on what machine/hardware?
- Reviewer / case organiser
- All tools / assigned tools (scoring algorithm requires you to know which is the fastest tool)
- Own hardware / SHARE VM

In case reviewers will do the performance scoring: is there any tooling to extract the scores automatically from the generated output.tsv file?

**Comment by szarnyasg** [comment]
Hi!

I planned to conduct the performance measurements on our private cloud with Ubuntu VMs, same as described in our solution: "The benchmarks were performed on a 64-bit Ubuntu Server 14.04 virtual machine deployed on a private
cloud. The machine used a quad-core 2.50 GHz Xeon L5420 processor and 16 GB of memory. We used
Oracle JDK 8 and set the available heap memory to 15 GB."

There is no tooling for this yet -- this is a task for us to develop. I think it'll be a mixture of R code and Google spreadsheets.

Gabor

**Comment by georghinkel** [comment]
Hi Gabor,

if you want to measure the execution times on a private cloud, I would appreciate if you measured the NMF solution(s) on a Windows VM, since the Mono runtime on the ArchLinux SHARE VM showed awful performance results. Furthermore, Mono does not support memory meters and thus the memory metric always returns 0.

Georg

**Comment by szarnyasg** [comment]
Hi Georg!

I'll see what I can do about running the solution on a Windows VM.
Regarding the memory metrics -- never mind those, we did some profiling and they turned out to be extremely inaccurate. We tried some setups (e.g. invoking the GC by hand) but couldn't really outsmart the garbage collector. Setting a heap limit and seeing the application crash on an OutOfMemoryException is the surefire way of getting a good picture of the actual memory consumption. 

Gabor

**Comment by istvanrath** [comment]
> Getting a heap limit and seeing the application crash on an OutOfMemoryException is the surefire way of getting a good picture of the actual memory consumption.

... a surefire way to see _one aspect_ of memory consumption. Actually, for technologies like .NET and Java you really need a profiler (even the built-in ones like JConsole can do well for this purpose).

The reason why Gabor uses so much RAM is good: to reduce the effect of GCs and thrashing on runtime performance as much as possible. Things like "how much memory is minimally needed to execute the scenario", "how much memory is used after the execution is done", "how much memory is typically allocated if there is plenty" etc. should be measured in separate measurement runs as various JVM settings (heap limits, GC strategies) and the presence of a profiler can interfere with performance measurements.

**Comment by szarnyasg** [comment]
@georghinkel, did you try to run your solution on a Linux VM with a lot of memory? The SHARE image is very low on memory.

Also, did you experiment with Microsoft's .NET Core for Linux (https://github.com/dotnet/coreclr/blob/master/Documentation/get-dotnetcore-dnx-linux.md)?

**Comment by szarnyasg** [comment]
@georghinkel

**Comment by georghinkel** [comment]
I sparsely tested the solution on a machine with a lot of memory, but I did not invest as much time as I would have liked. The machine I used for testing ran Ubuntu 12.04 with Mono, though I am not which version and is equipped with a CPU clocked at 2,8Ghz and I believe 16GB RAM. There, the solution ran also quite slowly, at least for the incremental version (the batch version is quite fast). However, it is some weeks already that I did this and I cannot completely remember what model sizes I used for testing, sorry. I will redo the run as soon as I have access to this machine again, which should be on Monday.
